# Generated by Django 3.1.7 on 2021-08-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='NotesModel',
        ),
    ]
