# Generated by Django 3.1.7 on 2021-08-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0002_auto_20210806_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesmodel',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
