# Generated by Django 3.1.7 on 2021-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20210808_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
